### PR TITLE
Add SOAP ROM to Bliss Family Projects

### PR DESCRIPTION
**Pull request by sixohtew**

### CODE REVIEW

**Comment by sixohtew** [comment]
@Makaveli-The-Dev can i have full write access for blissroms github?

**Comment by sixohtew** [comment]
didnt know that, changed and ready to be pushed

**Comment by ideaman924** [comment]
Photobucket has request limitations, possibly move that image somewhere else like imgur

**Comment by electrikjesus** [comment]
These have been added to the site

**Pull request closed without merging**
