### PR TITLE
Bliss Banner Update

### PR DESCRIPTION
**Pull request by StudioKeys**
Here, the banner is declared locally in one of my repos and the banner looks better than the one present as the new one gives a common linkage between BlissROMs and BlissOS.

### CODE REVIEW

**Comment by ericswpark** [comment]
@StudioKeys thank you for the contribution. However, in your original PR, I was referring to adding the PNG file to this repository instead of your own. You can do this in a single PR – add the PNG file, make the link change, commit, and then push the patch as a pull request. Let me know if you can't do this.

**Comment by StudioKeys** [comment]
Ok i will try my level best :)

**Comment by StudioKeys** [comment]
@ericswpark as you said before, you as a person with write auth can add files to the repo while i cant do it so it makes things a bit hard so ig its better to do it by your way i.e., doing the change by yourself

**Comment by StudioKeys** [comment]
You are free to close the PR once you have read it :)

**Comment by ericswpark** [comment]
@StudioKeys you can add files to the repo by submitting a pull request. You don’t even need to create a separate one.

I’m guessing you are using the GitHub web interface to make your changes? In that case, you won’t be able to make the changes in one commit, but that’s okay. Here’s a workaround:

1. Go to the forked repository
2. Switch to the `patch-2` branch
3. Upload files and make more changes there

Since this PR is connected to that branch, any new changes you make will show up here. Again, you don’t even need to make a separate PR. Let me know if that works and I’ll squash and merge your changes.

**Comment by StudioKeys** [comment]
Let me see this possibility and yes i am using Github web interface.

**Comment by StudioKeys** [comment]
@ericswpark its all updated and set on the patch-2 branch as you mentioned :)

**Comment by ericswpark** [comment]
@StudioKeys thank you for your contribution. I appreciate you trying to learn the process of submitting pull request.

In the future, you may be better served by trying to make changes locally with the git client on your computer, instead of relying on GitHub's webGUI. Of course, it's just a suggestion; use what you're comfortable with!

**Comment by StudioKeys** [comment]
Yea i am learning use of Github on Desktop :)

**Pull request merged**
